F = 0
T = 0
G = 20
EM_CIMA_PISOS_ELEVADOS = False
ACELERACAO_Y = 0
ACELERACAO_Y_INIMIGO = 0
ACELERACAO_Y_LUTADOR = 0
VELOCIDADE = 10
PULANDO = False
ALTURA_MAX_PULO = 200

TARGET_FPS = 60

BLOCO_CHAO = 0