# TELA
LARGURA = 1200
ALTURA = 600

G = 20
F = 0
ACELERACAO = 0
BLOCO_C = 544
T = 0
# -------------------------------------------------- VARIAVEIS DO PERSONAGEM PRINCIPAL ------------------------------------------- #
VELOCIDADE = 10
POSICAO_X = 250
POSICAO_Y = 444
POSICAO_X_PERSONAGEM = 250
INDEX_MAGO = 0

POSICAO_INICIAL_X = 100
POSICAO_INICIAL_Y = 544
TESTE_Y = 100
EM_CIMA_DO_BLOCO = False

ALTURA_DO_PULO = 30
GRAVIDADE = 2


VELOCIDADE_ATAQUE = 15
INDEX_ATAQUE1 = 0
# --------------------------------------------fim: VARIAVEIS DO PERSONAGEM PRINCIPAL ------------------------------------------- #
# CONF GAME
FRAME = 0
RODANDO = True

BLOCO2 = 340


# ----  LUTADOR ----#
POSICAO_LUTADOR_X = 1000
POSICAO_LUTADOR_Y = 440
POSICAO_LUTADOR_X_INICIAL = 1000
POSICAO_LUTADOR_Y_INICIAL = 440
SIZE_LUTADOR = (140, 140)
VELOCIDADE_LUTADOR = 4

BLOCO_VIDA = (17, 18)
# VARIAVEIS DE LUTA
DANO = 10
BLOCO_DE_VIDA = 15
DIMINUI_VIDA = 15

DANO_MAGICO_1 = 30 
LUTADOR_SOFREU_DANO = False

VIVO_INIMIGO = True
# variaveis de interface
ESTADO_JOGO = 'INICIAR'
FONTE = (80, 30)
POS_COMECAR = [500, 430]
POS_SAIR = [500, 465]
POS_RECOMECAR = [550, 500]

POSICAO_INICIAL_X_INIMIGO2 = 0
ATACAR_MAGO = False
